name = "Davis"
age = 10
weight = 35.3
student = True
friends = "Jimmy Lucas Teddy"
hobbies = "ping pong fotball coding gaming"

print("name", name)
print(type(name))
print("age ", age)
print(type(age))
print("weight", weight)
print(type(weight))
print("student", student)
print(type(student))
print("friends",friends)
print(type(friends))
print("hobbies", hobbies)
print(type(hobbies))